### ISSUE TITLE
Option to start second

### ISSUE THREAD

**Issue by davidkowalk** [shridharrhegde/chain-reaction-ai#3]
I would like to suggest the option for the player to start second. Currently the game only supports the player to start first.

**Comment by notshridhar** [comment]
Hello @davidkowalk! Thanks for the suggestion!

That is a good option to enable the player to start second. However in the longer run, if we plan to expand the game to N players, this option might not be generic enough to handle the multiple configurations that might arise then. Personally, I would prefer having a `player_order` option instead, which accepts the list of players (thus deprecating `enemy` argument too).

But it is a perfectly fine option for now, so I am merging this feature to stable.

**Comment by davidkowalk** [comment]
Cool :D

An arbitrary number of players would bw cool.

Also, in hindsight --swapplayers would have been a better name.
