### ISSUE TITLE
Game menu and in-game feature

### ISSUE THREAD

**Issue by tanishaaaaaaaah** [shridharrhegde/chain-reaction-ai#6]
Can you add a menu in the start of the pygame window which allows to select the agents and start the game? And also a pause button  and timer while the game is on?

**Comment by akshayrcc** [comment]
Hello! I have added the selection menu for the AI agents using terminal inputs.

**Comment by tanishaaaaaaaah** [comment]
Thanks a lot @akshaychaudhari !! :D
